官网url: [https://www.python.org/dev/peps/pep-0342/](https://www.python.org/dev/peps/pep-0342/)

[TOC]

## PEP 342 -- Coroutines via Enhanced Generators(通过增强的生成器来实现协程)

-- | --
-- | --
PEP: | 342
标题: | 通过增强的生成器来实现协程
作者: | 	Guido van Rossum, Phillip J. Eby
状态: | Final
类型: | Standards Track
创建时间: | 2005-5-10
Python版本: | 2.5
Post-历史 | 

### Introduce(介绍)

这篇PEP目的是为生成器的API和语法作一些改进，让它们可以用作于简单的协程。这篇PEP不过是组合了另两篇没有通过的PEP，如果这篇PEP被实现的话它们就有些多余了：

- [PEP288](https://www.python.org/dev/peps/pep-0288)，生成器属性和异常。这篇PEP涉及了PEP288的下半部分，生成器的异常(事实上，`throw()`这个方法名就来自于PEP288).PEP342替关于生成器属性方面使用了另外的实现，不过，另一个概念也是来自于PEP288，即`yield`表达式。
- [PEP325](https://www.python.org/dev/peps/pep-0325)，关于生成器对资源释放的支持(resource-release)的支持。PEP342零散的收集了PEP325规范的一些细节，让它们更适合真正的实现方式。

### Motivation(动机)

对于很多算法的表达，协程是一个更自然的方式，比如模拟仿真(simulations)，游戏，异步I/O，以及其它形式的事件驱动(event-driver)编程和合作式的多任务处理(co-operative multitasking)。Python的生成器函数几乎就是协程－－但并不是－－它都允许在产出一个值之前暂停执行，但是在执行恢复时没有提供方式来传入传入值或异常。它不允许在`try/finallly`代码块的`try`部分暂停执行，这让协程流产后没有办法进行自我清理。

另外，生成器不可以在其它函数执行时交出控制权，除非那些函数也是生成器函数，必须让外层的生成器来负责输出内层生成器yield出的值。这种方式很复杂，要么调用函数时让生成器堵塞(不交出控制权)，或者对每个函数调用再加入一些重复冗余的代码。

不过，如果可以在一个生成器暂停时为它传入值或者异常，然后使用一个简单的协程规划器或者*蹦床函数*(trampoline function)即可以让每个协程可以非堵塞的被调用－－对于异步应用来说是一个好消息。这种应用可以编写协程来作一些非堵塞socket I/O，在数据获取之前都将控制权交由一个I/O规划器来掌握即可。与此同时，应用的I/O操作就像下面的代码一样简单:

```python
data = (yield nonblocking_read(my_socket, nbytes))
```

*想要停止代码的执行，需要等待`nonblocking_read()`协程生成一个值才行*.

总而言之，通过对语言的生成器－迭代器类型(generator-iterator type)作一些轻微改进，Python可以支持一种更加简单的异步代码编写方式，不需要繁琐的回调，不需要对程序使用resource-intensive线程来开启成百上千个多任务伪线程。因此，不需要对CPython的内核和API作大量改动，这些简单改进就可以让标准的CPython享受到Stackless Python的一些优势。另外，这些改进也可以加入到其它支持生成器的Python实现中(如Jython).

### Specification Summary(规范总结)

通过为生成器-迭代器类型加入一些简单的方法，作两个微小的语法调整，Python开发者就可以使用生成器函数来实现协程或其它形式的协作式多任务处理。下面是加入的方法和调整的语法:

1. 将`yield`重新定义为一个表达式，而不是之前的语句。目前的`yield`语句将会变为表达式，它的值自然也扔掉了。无论何时对生成器调用普通的`next()`让它重启后，`yield`表达式的值都是`None`.
2. 为generator-iterator加入一个`send()`方法，它会重启这个迭代器并发送一个值作为当前`yield`表达式的结果。`send()`方法返回生成器下一次yield的值，或者在生成器消耗完毕时抛出`StopIteration`.
3. 为generator-iterator加入一个`throw()`方法，它可以在生成器暂停并返回下一个值的时候抛出异常，如果生成器消耗完毕将会抛出`StopIteration`(如果没有捕获到传入的异常，或者抛出了一个其它的异常，那么这个异常将会向上传播给调用者).
4. 为generator-iterator加入一个`close()`方法，它会在生成器暂停时候抛出一个`GeneratorExit`异常。如果生成器抛出了`StopIteration`(正常结束，或者已经结束)或者抛出了`GeneratorExit`(没有捕获到异常)，那么就会返回给它的调用者。如果生成器yield了一个值，将会抛出`RuntimeError`.如果生成器抛出任何其它异常，都会向上传播给调用者。如果生成器已经退出那么`close()`就什么也不会做。
5. 当一个generator-iterator被垃圾回收后，让它自动调用`close()`。
6. 让`yield`可以用在`try/finally`代码块中，现在垃圾回收和`close()`都可以在`finally`字句中执行。

关于所有这些的原型实现都可以在Python**源代码patch #1223381**中看到。

### Specification: Sending Values into Generators(规范：将值发送到生成器中)

#### New generator method:send(value)(新的生成器方法:send(value))

提议为generator-iterator加入一个新的方法，叫做`send()`。它只接受一个参数，这个参数是需要送往生成器的值。调用`send(None)`等同于调用生成器的`next()`方法。使用其它值调用`send()`也是一样的，除了这个生成器本次yield的值不一样。

因为generator-iterator在生成器函数中由上至下执行，当这个生成器创建完毕以后没有办法让它的yield表达式再去接受一个值。因此，在一个generator-iterator开启时不允许以非`None`的参数来调用`send()`，如果这样调用了会出现一个`TypeError`(假定是某种逻辑错误)。因此，你在与一个协程通讯时，你必须在它的第一个yield表达式之前调用`next()`或者`send()`.

和`next()`一样，`send()`方法同样返回这个generator-iterator下一个yield的值，或者在迭代器消耗完毕或已经退出时以后抛出`StopIteration`。如果生成器抛出一个未捕获的异常，会向上传播给`send()`的调用者。

#### New syntax: Yield Expressions(新语法：Yield表达式)

Yield如果作为语句，是不能作为赋值语句的右半部分的；因此它被重新定义为表达式。这个yield表达式的值一般是`None`，除非`send()`通过一个非`None`的参数来调用。

Yield表达式应该总是被括号包裹，除非它出现在一个赋值语句的右侧顶端(只有这个yield表达式):

```python
x = yield 42
x = yield
x = 12 + (yield 42)
x = 12 + (yield)
foo(yield 42)
foo(yield)
```

上面的语句都是合法的。但是下面的语句都是不合法的:

```python
x = 12 + yield 42
x = 12 + yield
foo(yield 42, 12)
foo(yield, 12)
```

注意yield语句或者yield表达式没有表达式时也是合法的。这在逻辑上讲得通。当信息流在`next()`调用后被颠倒，它应该需要yield一下，不需要传入一个显式的其它值(`yield`其实等同于`yield None`).

当`send(value)`被调用后，`yield`表达式会重启并返回传入的值。当调用`next()`时，这个重启的`yield`表达式会返回一个`None`值。如果yield表达式是一个yield语句，这个返回的值就会被忽略，就像把函数调用当做语句使用的时候。

事实上，一个yield表达式就像是一个反向的函数调用；yield的参数事实上就是由当前执行的函数返回(yield)的，yield返回的值是传入到`send()`的参数。

注意：yield的语法扩展让它使用起来很像Ruby中的这个关键字。这是有意为之的。请记住在Python中想要block的传入(block passes)一个值到生成器，需要使用`send(EXPR)`而不是`return EXPR`，然后底层的机制将会控制生成器的传入啊，block机制也完全不同。block在Python中并不完全是thunks(形式装换函数)的意思；因为`yiled`将会暂停生成器frame的的执行。一些极端的情况也和Ruby不太一样；在Python中你不能保存一个block供稍后使用，你也不能测试它是否是一个block.(这里没地方写太多东西了，可能Guido可以把block讲解的更加清楚一些)。

### Specification: Exception and Cleanup(规范：异常和清理工作)

让生成器对象定义为由生成器函数生成的迭代器。下面的内容中，`g`只是指代为一个生成器对象。

#### New Syntax: yield allow inside try-finally(yield现在允许在try-finally语句中使用)

生成器函数扩展的语法允许在一个`try-finally`语句中使用`yield`语句。

#### New generator method: throw(type, value=None, traceback=None)(一个新的生成器方法：throw)

`g.throw(type, value, traceback)`指定一个特定的异常，它会在生成器`g`当前暂停的时候抛出(也就是说，在一个yield语句中，或者执行一个函数的body但还没有调用`next()`的时候)。如果生成器捕获了这个异常并yield了一个其它的值，这个值将会由`g.throw()`返回。如果没有捕获这个异常，`throw()`也会抛出同样的异常。如果生成器抛出了其它异常(包括`StopIteration`)，这个异常也会由`throw()`抛出。总而言之，`throw()`很像`send()`和`next()`，除了它会在暂停的那个时候抛出异常。如果生成器已经是关闭(closed)状态，`throw()`会直接抛出异常，表明它没有执行任何的生成器代码。

抛出异常的效果和下面这条语句一样:

```python
raise type, value, traceback
```

将会在生成器暂停的时候(suspension point)执行。`type`参数不能是`None`，`type`和`value`也必须能够兼容。如果`value`不是`type`的实例，将会使用这个value创建一个新的异常实例，创建的规则也和`raise`语句一样样的。如果提供了`traceback`参数，必须是一个合法的Python traceback对象，否则会抛出一个`TypeError`。

注意：选择`throw()`这个方法名称有多方面的考虑。`Raise`是一个关键字所以不适合再去做方法名。而且`throw()`会首先重启生成器，然后再抛出异常，这点也和`raise`不一样，后者是立即抛出异常。`throw`这个词语也可以看做是把异常放到另一个位置上面，并且已经在其它语言中使用过。

其它考虑过但没有选择的方法名包括：`resolve()`，`signal()`，`genraise()`以及`flush()`。它们看起来都不如`throw()`这样合适。

#### New standard exception: GeneratorExit(新的标准异常：GeneratorExit)

定义了一个全新的标准异常：`GeneratorExit`，继承自`Exception`。一个生成器在结束时要么抛出这个异常，要么抛出`StopIteration`。

#### New generator method:close()(新的生成器方法：close)

下面是定义`g.close()`的伪代码:

```python
def close(self):
    try:
        self.throw(GeneratorExit)
    except (GeneratorExit, StopIteration):
        pass
    else:
        raise RuntimeError('generator ignored GeneratorExit')
    # 其它异常没有捕获
```

#### New generator method: \_\_del\_\_()(新的生成器方法：\_\_del\_\_)

`g.__del__()`是`g.close()`的封装。会在垃圾回收的时候调用这个方法(在CPython中，意味着它的引用计数为0的时候)。如果`close()`抛出异常，将会打印这个异常的traceback到`sys.stderr`；在垃圾回收时触发的异常不会再向上传播。这种删除时候的异常处理机制和类实例保持了一致。

如果生成器对象加入了一个循环(cycle)，`g.__del__()`可能不会被调用。这是当前CPython的垃圾回收策略。原因是GC需要打破这个cycle才可以回收它。

注意，在实践中不太可能出现生成器加入到一个cycle的情况。不过，如果你将一个生成器对象存储到一个全局变量就会创建一个cycle，通过生成器frame的`f_globals`指针来创建。另一个创建cycle的情况是，把这个生成器对象的引用放到一个数据结构中，然后以参数的形式传入到这个生成器中(比如，如果一个对象有一个方法是生成器，这个方法持有了由这个方法创建的迭代器引用)。这些方法在一般的生成器使用中都不太可能会发生。

另外，在这篇PEP的C实现中，无论一个生成器是因为错误还是正常退出而终止，它使用的frame对象都会被释放(release)。这种机制保证了生成器不会重启去做一些不可回收引用循环(uncollectable reference cycle)的剩余部分。可以让`close()`在`try/finally`或者`with`语句(请看PEP343)使用，让给定的生成器可以正常的结束。

### Optional Extensions(可选的扩展)

#### The Extended continue statement(contitnue语句的扩展)

这篇PEP的早期草案提到了一个新的`continue EXPR`语法，可用于for循环(来自于PEP340的想法)，可以讲迭代的值传入到EXPR中。这个特性被暂时的取消了，因为这篇PEP的焦点只放在如何把值传入到generator-iterator中，不包括其它的迭代器。Python-dev邮件列表中提到的一些特殊特性也考虑了，但是还过于早熟，还不是合适的时候。

### Open Issues(开放的问题)

Python-dev邮件列表中的讨论揭露了一些开放性的问题。都在下面提出来了，并且加入了我个人偏爱的解决方案和它的积极性:

1. 如果在生成器响应`GeneratorExit`异常的时候yield了另一个值，`close()`方法应该抛出什么异常?

    最开始我选择了`TypeError`因为可以代表是生成器函数的一种严重不当行为(gross misbehavior)，需要通过修改代码来修复。但是在PEP343中的`with_template`装饰器类对类似的情况使用了`RuntimeError`.那么它们当然应该使用同一个异常.我没有专门为这个情况引入一个新的标准异常的打算,因为我们不想让用户捕获这个异常:我们只想让中在traceback被清晰地打印出来，让程序员知道如何修复代码。所以我任务应该使用`RuntimeError`。对此还有些先例：这个异常会由Python代码发现无尽递归时抛出,对于未初始化的对象也会抛出这个异常(以及很多杂七杂八的情况)。
    
2. 





